name: Deploy to cloudtype
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: moa/2nd-semester-project-be-2
          stage: main
          yaml: |
            name: moa
            app: java@11
            options:
              ports: "8080"
              env:
                - name: uploadPath
                  var: uploadPath
                - name: photoImageLocation
                  var: photoImageLocation
                - name: DB_url
                  value: svc.sel5.cloudtype.app
                - name: DB_port
                  value: "31600"
                - name: DB_dataBaseName
                  value: moa
                - name: DB_name
                  value: root
                - name: DB_password
                  value: moamoa1122
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
